### ISSUE TITLE
Lats & Longs less than +1 minute are in the wrong direction

### ISSUE THREAD

**Issue by richorama** [dbarbalato/magellan#7]
These lines fail when added to the test suite:

```js
assert.equal('N', magellan(0.1).latitude().coordinate.direction);
assert.equal('E', magellan(0.1).longitude().coordinate.direction);
```

They are evaluated at `S` and `W` respectively.

**Comment by captivationsoftware** [comment]
Good find -- do you want to take a stab at it or wait for me to get around to it?

**Comment by richorama** [comment]
I'll give it a go, and get back to you in the next day or two :¬)
